message: Hello your order is getting processed.. Thank You. Visit Again.

CART_DB_URL: jdbc:h2:mem:cartdb

PRODUCT_DB_URL: jdbc:h2:mem:productdb

ORDER_DB_URL: jdbc:h2:mem:orderdb

CART_MS_ACTIVE_PROFILE: qa

